=== MarceloNunesAlves/ace/ace/etc/events.dtd
<!-- root element: list of events -->
<!ELEMENT events (event*)>

<!-- level 1: event -->
<!ELEMENT event (name,description,id,type,status,count?,host,creation,
                 attributes?,references?,history?)>

<!-- level 2 -->
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT count (#PCDATA)>
<!ELEMENT host (#PCDATA)>
<!ELEMENT creation (#PCDATA)>
<!ELEMENT attributes (attribute)*>
<!ELEMENT references (reference)*>
<!ELEMENT history (historyentry)*>

<!-- level 3 -->
<!ELEMENT attribute (#PCDATA)>
<!ATTLIST attribute key CDATA #REQUIRED>
<!ELEMENT reference (#PCDATA)>
<!ATTLIST reference type (parent|child|cross) #REQUIRED>
<!ELEMENT historyentry (rule,host,timestamp,fields?,reason?)>

<!-- level 4 -->
<!ELEMENT rule (groupname,rulename)>
<!ELEMENT timestamp (#PCDATA)>
<!ELEMENT fields (field*)>
<!ELEMENT reason (#PCDATA)>

<!-- level 5 -->
<!ELEMENT groupname (#PCDATA)>
<!ELEMENT rulename (#PCDATA)>
<!ELEMENT field (#PCDATA)>

=== MarceloNunesAlves/ace/ace/tests/test_101_events.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
<!DOCTYPE events SYSTEM "events.dtd">
-->
<!-- some independent, fictional events -->
<events>
	<event>
		<name>NIC:ETHERNET:LINKUP</name>
		<description>The ethernet network internet controller is up.</description>
		<id>e9294e806d02fd8ebd90e345434c16a3</id>
		<type>raw</type>
		<status>active</status>
		<host>host-a-0</host>
		<creation>1243039102</creation>
		<attributes>
			<attribute key="interface">1</attribute>
		</attributes>
	</event>
	<event>
		<name>MAIL:FRESHCLAM:ERROR</name>
		<description>The anti-virus signatures could not be updated.</description>
		<id>ae84e1e89470ddd1ecaf33ffb1b7538f</id>
		<type>raw</type>
		<status>inactive</status>
		<host>host-b-0</host>
		<creation>1244014810</creation>
		<history>
			<historyentry>
				<rule>
					<groupname>freshclam</groupname>
					<rulename>detect-single-events</rulename>
				</rule>
				<host>host-b-0</host>
				<timestamp>1244014940</timestamp>
				<fields><field>status</field></fields>
				<reason>Single errors can be ignored.</reason>
			</historyentry>
		</history>
	</event>
</events>

<!--
vim: sw=2 ts=2
-->
